export default{
    // 分享文案
	share: () => ({
			title: '广州租房小利器来了！',
			desc: '广州租房小利器来了！快来一键查询广州地铁站点附近租金',
			link: location.href.match(/.*game_id\/\d+/) && location.href.match(/.*game_id\/\d+/)[0],
			imgUrl: 'http://24haowan-cdn.shanyougame.com/dingzhi/subway/share.png',
		}),
	imgs: ['img/bg-banner.png',
        'img/bg-banner2.png',
        'img/bg-end.png',
        'img/bg-home.jpg',
        'img/bg-main.png',
        'img/bg-select.png',
        'img/btn/btn10_true.png',
        'img/btn/btn1_true.png',
        'img/btn/btn2_true.png',
        'img/btn/btn3_true.png',
        'img/btn/btn4_true.png',
        'img/btn/btn5_true.png',
        'img/btn/btn6_true.png',
        'img/btn/btn7_true.png',
        'img/btn/btn8_true.png',
        'img/btn/btn9_true.png',
        'img/btn/btn_10_false.png',
        'img/btn/btn_10_true.png',
        'img/btn/btn_1_false.png',
        'img/btn/btn_1_true.png',
        'img/btn/btn_2_false.png',
        'img/btn/btn_2_true.png',
        'img/btn/btn_3_false.png',
        'img/btn/btn_3_true.png',
        'img/btn/btn_4_false.png',
        'img/btn/btn_4_true.png',
        'img/btn/btn_5_false.png',
        'img/btn/btn_5_true.png',
        'img/btn/btn_6_false.png',
        'img/btn/btn_6_true.png',
        'img/btn/btn_7_false.png',
        'img/btn/btn_7_true.png',
        'img/btn/btn_8_false.png',
        'img/btn/btn_8_true.png',
        'img/btn/btn_9_false.png',
        'img/btn/btn_9_true.png',
        'img/btn/btn_false.png',
        'img/btn-main.png',
        'img/btn-sec.png',
        'img/distance.png',
        'img/dot/dot.png',
        'img/dot/dot1.png',
        'img/dot/dot2.png',
        'img/dot/dot3.png',
        'img/dot/dot4.png',
        'img/dot/dot5.png',
        'img/dot/dot6.png',
        'img/dot/dot7.png',
        'img/dot/dot8.png',
        'img/dot/dot9.png',
        'img/icon-active-top.png',
        'img/icon-loading.png',
        'img/icon-share.png',
        'img/icon_distance_true.png',
        'img/icon_loupan_true.png',
        'img/logo-bottom.png',
        'img/paper.png',
        'img/printer.png',
        'img/title-result.png',
        'img/picker-mask.png'],
	audios: [

    ],
	theme: {
		'1号线': 'rgb(251,237,33)',
		'2号线': 'rgb(80,117,221)',
		'3号线': 'rgb(250,175,59)',
		'4号线': 'rgb(50,186,121)',
		'5号线': 'rgb(210,47,60)',
		'6号线': 'rgb(131,90,175)',
		'7号线': 'rgb(0,168,156)',
		'8号线': 'rgb(41,170,225)',
        '9号线': 'rgb(255,255,149)',
		'广佛线': 'rgb(139,197,63)',
	},
};
